service: vmtp-users

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, self:custom.defaultStage}
  deploymentBucket: vm-slsdeploymentbucket-${self:provider.region}
  environment:
    USERS_TABLE: ${self:custom.usersTableName}
    REGION: ${self:provider.region}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.usersTableName}"
plugins:
- serverless-plugin-git-variables
- serverless-plugin-dynamodb-autoscaling
- serverless-prune-plugin

custom:
  gitDescription: ${git:repository} - ${git:branch} - ${git:tags}
  usersTableName: ${self:service}-${sls:stage}
  dynamodbAutoscaling:
    tablesConfig:
      usersTable:
        table:
          minCapacity: 10
          maxCapacity: 1000
          targetUsage: 0.5


functions:

  list:
    handler: src/handlers.listUsers
    events:
      - httpApi:
          path: /users/list
          method: get

  get:
    handler: src/handlers.getItem
    events:
      - httpApi:
          path: /users/get/{id}
          method: get

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 10
          WriteCapacityUnits: 10